server:
  port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: user-microservice
  cloud:
    config:
      profile: dev

appDescription: "Pragma Power-up"
appVersion: "1.0.0"


jwt:
  secret: secret
  expiration: 3600

