server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_microservice
    username: root
    password:

  security:
    user:
      name: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Power-up"
appVersion: "1.0.0"

jwt:
  secret: secret
  expiration: 3600

