server:
  port: 8091

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: small-square-microservice
  cloud:
    config:
      profile: dev

appDescription: "Pragma Power-up"
appVersion: "1.0.0"


